[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nonebot-plugin-helper-recall"
version = "0.2.0"
description = "帮助普通群员撤回自己超时无法撤回的消息"
authors = [{name = "Wojusensei", email = "3442006415@qq.com"}]
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "nonebot2>=2.3.0",
    "nonebot-adapter-onebot>=2.0.0",
]
requires-python = ">=3.10"

[project.optional-dependencies]
test = [
    "pytest>=8.0,<9",
    "pytest-asyncio",
    "nonebug>=0.4.0",
]

[project.urls]
Homepage = "https://github.com/Wojusensei/nonebot-plugin-helper-recall"

[tool.setuptools]
packages = ["nonebot_plugin_helper_recall"]
